### ISSUE TITLE
Plugin interface

### ISSUE THREAD

**Issue by willviles** [kolybasov/ember-medium-editor#3]
I've started refactoring ember-medium-editor-insert ([1.0.0-refactor branch](https://github.com/willviles/ember-medium-editor-insert/tree/1.0.0-refactor)) to be compatible with this plugin and there are a few places where I'd like to discuss how best to interface with Ember Medium Editor:

## Passing plugin options

It'd be neat to pass plugin options via the existing options hash. Perhaps a nested `plugins` object?

```handlebars
{{medium-editor
    model.text
    options=options
}}
```

```js
controller.set('options', {
  plugins: {
    pluginName: {
      foo: true,
      bar: false
    }
  }
});
```

## Initializing Plugins

Plugins then could reopen the `medium-editor` component in an initializer, call `this._super(...arguments)` on `_initEditor` and initialize inside there if its options are provided.

```js
import MediumEditor from 'ember-medium-editor/components/medium-editor';

export function initialize() {
  MediumEditor.reopen({
    _initEditor() {
      this._super(...arguments);
     
      // Check if plugin options are set
      let options = Ember.get(this, 'options.plugins.pluginName');
      if (Ember.typeOf(options) !== 'object') { return; }
      
      // If so, initialize
      new Plugin({
        editor: this.get('_editor')
      });

    }
  });
}

export default {
  name: 'plugin',
  initialize: initialize
};

```

Check out my Ember Medium Editor Insert example [here](https://github.com/willviles/ember-medium-editor-insert/blob/1.0.0-refactor/app/initializers/medium-editor-insert.js).

**Comment by kolybasov** [comment]
@willviles I've invited you as collaborator. We can think together how to implement plugins interface. Also you can respond to other issues as well :)

**Comment by willviles** [comment]
Awesome, thanks! 

I've been thinking. One alternative to having a plugin interface is integrating core plugins directly into Ember Medium Editor. [Ember Medium Editor Insert](https://github.com/willviles/ember-medium-editor-insert) and [Ember Medium Editor Button](https://github.com/willviles/ember-medium-editor-button) are both pretty core plugins, so perhaps we could just include the necessary dependencies should they be enabled in `ember-cli-build`?

```javascript
// ember-cli-build.js
let app = new EmberApp(defaults, {
  mediumEditor: {
    excludeStyles: false,
    theme: 'default',
    plugins: [
      'insert',
      'custom-buttons'
    ]
  }
});
```
