### ISSUE TITLE
onChange event is triggered on first render

### ISSUE THREAD

**Issue by n1ru4l** [kolybasov/ember-medium-editor#4]
Is this intended?

**Comment by kolybasov** [comment]
Nope, it could be a bug.

**Comment by n1ru4l** [comment]
Also the event is fired when the value is changed externally. In my opinion the event should only be fired if the user is actively operating in the medium-editor area.

What do you think? I could do a pull request for this.

Here also a demonstration: https://ember-twiddle.com/9d1bc231c416e09202917a74f3a6d37e?openFiles=controllers.application.js%2C

**Comment by kolybasov** [comment]
@n1ru4l agree, onChange event was designed to trigger only when content changed inside of editor. It would be great if you can submit PR. Thanks!

**Comment by n1ru4l** [comment]
I am not able to create a failing test for this :/

In the test context the onChange event is never triggered.
```javascript
test('it should not fire onChange when content is changed externally', function(assert) {
  assert.expect(0);

  let done = assert.async();

  this.on('onChange', () => assert.ok(false));
  this.set('value', '<p>someValue</p>');
  this.render(hbs`{{medium-editor value onChange=(action "onChange")}}`);
  this.set('value', '<p>someVasdasdasdasdasalue</p>');

  setTimeout(done, 1000);
});
```
